version: 0.1
phases:
  install:
    commands:    
  pre_build:
    commands:
  build:
    commands:
    - cd sam-app ; make deps clean
  post_build:
    commands:
    - cd sam-app ; go test -v ./hello-world
    - cd sam-app ; make build
    # env var BUILD_ARTIFACT_BUCKET is defined in ci.yaml
    - aws cloudformation package
      --template-file sam-app/template.yaml
      --s3-bucket $BUILD_ARTIFACT_BUCKET
      --output-template-file SamDeploymentTemplate.yaml
artifacts:
  type: zip
  files:
  - SamDeploymentTemplate.yaml